Django/myfirst/myfirst/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:article_id>/', views.detail, name = 'detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name = 'leave_comment')
]

Django/myfirst/myfirst/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
	path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

Django/myfirst/myfirst/apps/articles/models.py
import datetime
from django.db import models

from django.utils import timezone

class Article(models.Model):
	article_title = models.CharField('Article name', max_length = 200)
	article_text = models.TextField('Article TXT')
	pub_date = models.DateTimeField('Date')
	
	def __str__(self):
		return self.article_title
	
	def was_published_recently(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))
	
	class Meta:
		verbose_name = 'Статья' 
		verbose_name_plural = 'Статьи'
	
class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	author_name = models.CharField('name', max_length = 50)
	comment_text = models.CharField('text', max_length = 200)
	
	def __str__(self):
		return self.author_name
	

	class Meta:
		verbose_name = 'Комментарий'
		verbose_name_plural = 'Комментарии'

Django/myfirst/myfirst/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse

from .models import Article, Comment

def index(request):
	latest_articles_list = Article.objects.order_by('-pub_date')[:5]
	return render(request, 'articles/list.html', {'latest_articles_list':latest_articles_list})
	
def detail(request, article_id):
	try:
		a = Article.objects.get( id = article_id )
	except:
		raise Http404("Статья не найдена!")
		
	latest_comments_list = a.comment_set.order_by('-id')[:10]
		
	return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})
	
def leave_comment(request, article_id):
	try:
		a = Article.objects.get( id = article_id )
	except:
		raise Http404("Статья не найдена!")
		
	Comment.objects.create(article = a, author_name = request.POST.get('name'), comment_text = request.POST.get('text'))
	
	return HttpResponseRedirect(reverse('articles:detail', args = (a.id,)))

Django/myfirst/myfirst/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}
<div class='allart'>

<div class="art">
<h2><ins>{{article.article_title}}</ins></h2>
	
<p>{{article.article_text}}</p>

<em>{{article.pub_date}}</em>
<span class="newart">
{% if article.was_published_recently %}
НОВАЯ СТАТЬЯ
{% endif %}
</span>
</div>

<span class="line_two">
<hr>
</span>

<div class='comment'>
{% if latest_comments_list %}
	
	{%for c in latest_comments_list %}
		<p>
			<strong><ins>{{c.author_name}}</ins></strong>
			<p>
				{{c.comment_text}}
			</p>
		</p>
	<hr class="line_before">
	{% endfor %}
{% else %}
Комментарии не найдены.
{% endif %}
</div>

<div class="table">
<form action="{% url 'articles:leave_comment' article.id %}" method="POST">

	{% csrf_token %}

	<input type="text" required placeholder="Ваше имя" name="name"><br>

	<style type="text/css">
		textarea[name="text"]{
			resize: none;
		}
	</style>

	<textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea><br>
	
	<button type="submit">Оставить комментарий</button>

</form>
</div>
</div>
{% endblock %}

Django/myfirst/myfirst/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Недавние новости{% endblock %}


{% block content %}
<div class="allart">
<div class="art">
<h2><ins>Articles list</ins></h2>
</div>
	{%if latest_articles_list %}
	<ol>
		{% for a in latest_articles_list %}
			<div class="art_list">
				<li>
				<a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a>
				<hr>
				</li>
			</div>
		{% endfor %}
	</ol>
	{% else %}
		Статьи не найдены )=
	{% endif %}
</div>
{% endblock %}

Django/myfirst/myfirst/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<link rel="stylesheet" type="text/css" href="{% static '\articles\css\style.css' %}">
	<meta charset="UTF-8">
	<title>{% block title %}Base{% endblock %}</title>
</head>
<body>
	{% block content %}{% endblock %}

</body>
</head>